// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TSDB.proto

package com.zhaoyuan.proto.auto;

/**
 * Protobuf type {@code com.zhaoyuan.proto.auto.BlobDLL}
 */
public final class BlobDLL extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.zhaoyuan.proto.auto.BlobDLL)
    BlobDLLOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BlobDLL.newBuilder() to construct.
  private BlobDLL(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BlobDLL() {
    date_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BlobDLL();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.zhaoyuan.proto.auto.TSDBProto.internal_static_com_zhaoyuan_proto_auto_BlobDLL_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.zhaoyuan.proto.auto.TSDBProto.internal_static_com_zhaoyuan_proto_auto_BlobDLL_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.zhaoyuan.proto.auto.BlobDLL.class, com.zhaoyuan.proto.auto.BlobDLL.Builder.class);
  }

  public static final int DATE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object date_ = "";
  /**
   * <code>string date = 1;</code>
   * @return The date.
   */
  @java.lang.Override
  public java.lang.String getDate() {
    java.lang.Object ref = date_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      date_ = s;
      return s;
    }
  }
  /**
   * <code>string date = 1;</code>
   * @return The bytes for date.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDateBytes() {
    java.lang.Object ref = date_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      date_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VALUE1_FIELD_NUMBER = 2;
  private double value1_ = 0D;
  /**
   * <code>double value1 = 2;</code>
   * @return The value1.
   */
  @java.lang.Override
  public double getValue1() {
    return value1_;
  }

  public static final int VALUE2_FIELD_NUMBER = 3;
  private double value2_ = 0D;
  /**
   * <code>double value2 = 3;</code>
   * @return The value2.
   */
  @java.lang.Override
  public double getValue2() {
    return value2_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(date_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, date_);
    }
    if (java.lang.Double.doubleToRawLongBits(value1_) != 0) {
      output.writeDouble(2, value1_);
    }
    if (java.lang.Double.doubleToRawLongBits(value2_) != 0) {
      output.writeDouble(3, value2_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(date_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, date_);
    }
    if (java.lang.Double.doubleToRawLongBits(value1_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, value1_);
    }
    if (java.lang.Double.doubleToRawLongBits(value2_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, value2_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.zhaoyuan.proto.auto.BlobDLL)) {
      return super.equals(obj);
    }
    com.zhaoyuan.proto.auto.BlobDLL other = (com.zhaoyuan.proto.auto.BlobDLL) obj;

    if (!getDate()
        .equals(other.getDate())) return false;
    if (java.lang.Double.doubleToLongBits(getValue1())
        != java.lang.Double.doubleToLongBits(
            other.getValue1())) return false;
    if (java.lang.Double.doubleToLongBits(getValue2())
        != java.lang.Double.doubleToLongBits(
            other.getValue2())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DATE_FIELD_NUMBER;
    hash = (53 * hash) + getDate().hashCode();
    hash = (37 * hash) + VALUE1_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getValue1()));
    hash = (37 * hash) + VALUE2_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getValue2()));
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.zhaoyuan.proto.auto.BlobDLL parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zhaoyuan.proto.auto.BlobDLL parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zhaoyuan.proto.auto.BlobDLL parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zhaoyuan.proto.auto.BlobDLL parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zhaoyuan.proto.auto.BlobDLL parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zhaoyuan.proto.auto.BlobDLL parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zhaoyuan.proto.auto.BlobDLL parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zhaoyuan.proto.auto.BlobDLL parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zhaoyuan.proto.auto.BlobDLL parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.zhaoyuan.proto.auto.BlobDLL parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zhaoyuan.proto.auto.BlobDLL parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zhaoyuan.proto.auto.BlobDLL parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.zhaoyuan.proto.auto.BlobDLL prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.zhaoyuan.proto.auto.BlobDLL}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.zhaoyuan.proto.auto.BlobDLL)
      com.zhaoyuan.proto.auto.BlobDLLOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhaoyuan.proto.auto.TSDBProto.internal_static_com_zhaoyuan_proto_auto_BlobDLL_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhaoyuan.proto.auto.TSDBProto.internal_static_com_zhaoyuan_proto_auto_BlobDLL_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhaoyuan.proto.auto.BlobDLL.class, com.zhaoyuan.proto.auto.BlobDLL.Builder.class);
    }

    // Construct using com.zhaoyuan.proto.auto.BlobDLL.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      date_ = "";
      value1_ = 0D;
      value2_ = 0D;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.zhaoyuan.proto.auto.TSDBProto.internal_static_com_zhaoyuan_proto_auto_BlobDLL_descriptor;
    }

    @java.lang.Override
    public com.zhaoyuan.proto.auto.BlobDLL getDefaultInstanceForType() {
      return com.zhaoyuan.proto.auto.BlobDLL.getDefaultInstance();
    }

    @java.lang.Override
    public com.zhaoyuan.proto.auto.BlobDLL build() {
      com.zhaoyuan.proto.auto.BlobDLL result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.zhaoyuan.proto.auto.BlobDLL buildPartial() {
      com.zhaoyuan.proto.auto.BlobDLL result = new com.zhaoyuan.proto.auto.BlobDLL(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.zhaoyuan.proto.auto.BlobDLL result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.date_ = date_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.value1_ = value1_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.value2_ = value2_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.zhaoyuan.proto.auto.BlobDLL) {
        return mergeFrom((com.zhaoyuan.proto.auto.BlobDLL)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.zhaoyuan.proto.auto.BlobDLL other) {
      if (other == com.zhaoyuan.proto.auto.BlobDLL.getDefaultInstance()) return this;
      if (!other.getDate().isEmpty()) {
        date_ = other.date_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getValue1() != 0D) {
        setValue1(other.getValue1());
      }
      if (other.getValue2() != 0D) {
        setValue2(other.getValue2());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              date_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 17: {
              value1_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            case 25: {
              value2_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object date_ = "";
    /**
     * <code>string date = 1;</code>
     * @return The date.
     */
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        date_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string date = 1;</code>
     * @return The bytes for date.
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string date = 1;</code>
     * @param value The date to set.
     * @return This builder for chaining.
     */
    public Builder setDate(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      date_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string date = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDate() {
      date_ = getDefaultInstance().getDate();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string date = 1;</code>
     * @param value The bytes for date to set.
     * @return This builder for chaining.
     */
    public Builder setDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      date_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private double value1_ ;
    /**
     * <code>double value1 = 2;</code>
     * @return The value1.
     */
    @java.lang.Override
    public double getValue1() {
      return value1_;
    }
    /**
     * <code>double value1 = 2;</code>
     * @param value The value1 to set.
     * @return This builder for chaining.
     */
    public Builder setValue1(double value) {

      value1_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>double value1 = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearValue1() {
      bitField0_ = (bitField0_ & ~0x00000002);
      value1_ = 0D;
      onChanged();
      return this;
    }

    private double value2_ ;
    /**
     * <code>double value2 = 3;</code>
     * @return The value2.
     */
    @java.lang.Override
    public double getValue2() {
      return value2_;
    }
    /**
     * <code>double value2 = 3;</code>
     * @param value The value2 to set.
     * @return This builder for chaining.
     */
    public Builder setValue2(double value) {

      value2_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>double value2 = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearValue2() {
      bitField0_ = (bitField0_ & ~0x00000004);
      value2_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.zhaoyuan.proto.auto.BlobDLL)
  }

  // @@protoc_insertion_point(class_scope:com.zhaoyuan.proto.auto.BlobDLL)
  private static final com.zhaoyuan.proto.auto.BlobDLL DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.zhaoyuan.proto.auto.BlobDLL();
  }

  public static com.zhaoyuan.proto.auto.BlobDLL getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BlobDLL>
      PARSER = new com.google.protobuf.AbstractParser<BlobDLL>() {
    @java.lang.Override
    public BlobDLL parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BlobDLL> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BlobDLL> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.zhaoyuan.proto.auto.BlobDLL getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

