// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TSDB.proto

package com.zhaoyuan.proto.auto;

public interface BlobDLOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.zhaoyuan.proto.auto.BlobDL)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string date = 1;</code>
   * @return The date.
   */
  java.lang.String getDate();
  /**
   * <code>string date = 1;</code>
   * @return The bytes for date.
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <code>double value = 2;</code>
   * @return The value.
   */
  double getValue();
}
