// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TSDB.proto

package com.zhaoyuan.proto.auto;

public interface BlobDLLOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.zhaoyuan.proto.auto.BlobDLL)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string date = 1;</code>
   * @return The date.
   */
  java.lang.String getDate();
  /**
   * <code>string date = 1;</code>
   * @return The bytes for date.
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <code>double value1 = 2;</code>
   * @return The value1.
   */
  double getValue1();

  /**
   * <code>double value2 = 3;</code>
   * @return The value2.
   */
  double getValue2();
}
