// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TSDB.proto

package com.zhaoyuan.proto.auto;

/**
 * Protobuf type {@code com.zhaoyuan.proto.auto.TSDBResponse}
 */
public final class TSDBResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.zhaoyuan.proto.auto.TSDBResponse)
    TSDBResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TSDBResponse.newBuilder() to construct.
  private TSDBResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TSDBResponse() {
    tsid_ = "";
    action_ = "";
    clz_ = "";
    data_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TSDBResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.zhaoyuan.proto.auto.TSDBProto.internal_static_com_zhaoyuan_proto_auto_TSDBResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.zhaoyuan.proto.auto.TSDBProto.internal_static_com_zhaoyuan_proto_auto_TSDBResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.zhaoyuan.proto.auto.TSDBResponse.class, com.zhaoyuan.proto.auto.TSDBResponse.Builder.class);
  }

  public static final int TSID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tsid_ = "";
  /**
   * <code>string tsid = 1;</code>
   * @return The tsid.
   */
  @java.lang.Override
  public java.lang.String getTsid() {
    java.lang.Object ref = tsid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tsid_ = s;
      return s;
    }
  }
  /**
   * <code>string tsid = 1;</code>
   * @return The bytes for tsid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTsidBytes() {
    java.lang.Object ref = tsid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tsid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACTION_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object action_ = "";
  /**
   * <code>string action = 2;</code>
   * @return The action.
   */
  @java.lang.Override
  public java.lang.String getAction() {
    java.lang.Object ref = action_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      action_ = s;
      return s;
    }
  }
  /**
   * <code>string action = 2;</code>
   * @return The bytes for action.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getActionBytes() {
    java.lang.Object ref = action_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      action_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TSTYPE_FIELD_NUMBER = 3;
  private int tstype_ = 0;
  /**
   * <code>int32 tstype = 3;</code>
   * @return The tstype.
   */
  @java.lang.Override
  public int getTstype() {
    return tstype_;
  }

  public static final int CLZ_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object clz_ = "";
  /**
   * <code>string clz = 4;</code>
   * @return The clz.
   */
  @java.lang.Override
  public java.lang.String getClz() {
    java.lang.Object ref = clz_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clz_ = s;
      return s;
    }
  }
  /**
   * <code>string clz = 4;</code>
   * @return The bytes for clz.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClzBytes() {
    java.lang.Object ref = clz_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clz_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESULT_FIELD_NUMBER = 5;
  private int result_ = 0;
  /**
   * <code>int32 result = 5;</code>
   * @return The result.
   */
  @java.lang.Override
  public int getResult() {
    return result_;
  }

  public static final int DATA_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private java.util.List<com.google.protobuf.Any> data_;
  /**
   * <code>repeated .google.protobuf.Any data = 6;</code>
   */
  @java.lang.Override
  public java.util.List<com.google.protobuf.Any> getDataList() {
    return data_;
  }
  /**
   * <code>repeated .google.protobuf.Any data = 6;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
      getDataOrBuilderList() {
    return data_;
  }
  /**
   * <code>repeated .google.protobuf.Any data = 6;</code>
   */
  @java.lang.Override
  public int getDataCount() {
    return data_.size();
  }
  /**
   * <code>repeated .google.protobuf.Any data = 6;</code>
   */
  @java.lang.Override
  public com.google.protobuf.Any getData(int index) {
    return data_.get(index);
  }
  /**
   * <code>repeated .google.protobuf.Any data = 6;</code>
   */
  @java.lang.Override
  public com.google.protobuf.AnyOrBuilder getDataOrBuilder(
      int index) {
    return data_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tsid_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tsid_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(action_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, action_);
    }
    if (tstype_ != 0) {
      output.writeInt32(3, tstype_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clz_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, clz_);
    }
    if (result_ != 0) {
      output.writeInt32(5, result_);
    }
    for (int i = 0; i < data_.size(); i++) {
      output.writeMessage(6, data_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tsid_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tsid_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(action_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, action_);
    }
    if (tstype_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, tstype_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clz_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, clz_);
    }
    if (result_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, result_);
    }
    for (int i = 0; i < data_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, data_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.zhaoyuan.proto.auto.TSDBResponse)) {
      return super.equals(obj);
    }
    com.zhaoyuan.proto.auto.TSDBResponse other = (com.zhaoyuan.proto.auto.TSDBResponse) obj;

    if (!getTsid()
        .equals(other.getTsid())) return false;
    if (!getAction()
        .equals(other.getAction())) return false;
    if (getTstype()
        != other.getTstype()) return false;
    if (!getClz()
        .equals(other.getClz())) return false;
    if (getResult()
        != other.getResult()) return false;
    if (!getDataList()
        .equals(other.getDataList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TSID_FIELD_NUMBER;
    hash = (53 * hash) + getTsid().hashCode();
    hash = (37 * hash) + ACTION_FIELD_NUMBER;
    hash = (53 * hash) + getAction().hashCode();
    hash = (37 * hash) + TSTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getTstype();
    hash = (37 * hash) + CLZ_FIELD_NUMBER;
    hash = (53 * hash) + getClz().hashCode();
    hash = (37 * hash) + RESULT_FIELD_NUMBER;
    hash = (53 * hash) + getResult();
    if (getDataCount() > 0) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getDataList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.zhaoyuan.proto.auto.TSDBResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zhaoyuan.proto.auto.TSDBResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zhaoyuan.proto.auto.TSDBResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zhaoyuan.proto.auto.TSDBResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zhaoyuan.proto.auto.TSDBResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zhaoyuan.proto.auto.TSDBResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zhaoyuan.proto.auto.TSDBResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zhaoyuan.proto.auto.TSDBResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zhaoyuan.proto.auto.TSDBResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.zhaoyuan.proto.auto.TSDBResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zhaoyuan.proto.auto.TSDBResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zhaoyuan.proto.auto.TSDBResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.zhaoyuan.proto.auto.TSDBResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.zhaoyuan.proto.auto.TSDBResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.zhaoyuan.proto.auto.TSDBResponse)
      com.zhaoyuan.proto.auto.TSDBResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhaoyuan.proto.auto.TSDBProto.internal_static_com_zhaoyuan_proto_auto_TSDBResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhaoyuan.proto.auto.TSDBProto.internal_static_com_zhaoyuan_proto_auto_TSDBResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhaoyuan.proto.auto.TSDBResponse.class, com.zhaoyuan.proto.auto.TSDBResponse.Builder.class);
    }

    // Construct using com.zhaoyuan.proto.auto.TSDBResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      tsid_ = "";
      action_ = "";
      tstype_ = 0;
      clz_ = "";
      result_ = 0;
      if (dataBuilder_ == null) {
        data_ = java.util.Collections.emptyList();
      } else {
        data_ = null;
        dataBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.zhaoyuan.proto.auto.TSDBProto.internal_static_com_zhaoyuan_proto_auto_TSDBResponse_descriptor;
    }

    @java.lang.Override
    public com.zhaoyuan.proto.auto.TSDBResponse getDefaultInstanceForType() {
      return com.zhaoyuan.proto.auto.TSDBResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.zhaoyuan.proto.auto.TSDBResponse build() {
      com.zhaoyuan.proto.auto.TSDBResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.zhaoyuan.proto.auto.TSDBResponse buildPartial() {
      com.zhaoyuan.proto.auto.TSDBResponse result = new com.zhaoyuan.proto.auto.TSDBResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.zhaoyuan.proto.auto.TSDBResponse result) {
      if (dataBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0)) {
          data_ = java.util.Collections.unmodifiableList(data_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.data_ = data_;
      } else {
        result.data_ = dataBuilder_.build();
      }
    }

    private void buildPartial0(com.zhaoyuan.proto.auto.TSDBResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.tsid_ = tsid_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.action_ = action_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.tstype_ = tstype_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.clz_ = clz_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.result_ = result_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.zhaoyuan.proto.auto.TSDBResponse) {
        return mergeFrom((com.zhaoyuan.proto.auto.TSDBResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.zhaoyuan.proto.auto.TSDBResponse other) {
      if (other == com.zhaoyuan.proto.auto.TSDBResponse.getDefaultInstance()) return this;
      if (!other.getTsid().isEmpty()) {
        tsid_ = other.tsid_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getAction().isEmpty()) {
        action_ = other.action_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getTstype() != 0) {
        setTstype(other.getTstype());
      }
      if (!other.getClz().isEmpty()) {
        clz_ = other.clz_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getResult() != 0) {
        setResult(other.getResult());
      }
      if (dataBuilder_ == null) {
        if (!other.data_.isEmpty()) {
          if (data_.isEmpty()) {
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureDataIsMutable();
            data_.addAll(other.data_);
          }
          onChanged();
        }
      } else {
        if (!other.data_.isEmpty()) {
          if (dataBuilder_.isEmpty()) {
            dataBuilder_.dispose();
            dataBuilder_ = null;
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000020);
            dataBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDataFieldBuilder() : null;
          } else {
            dataBuilder_.addAllMessages(other.data_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              tsid_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              action_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              tstype_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              clz_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              result_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              com.google.protobuf.Any m =
                  input.readMessage(
                      com.google.protobuf.Any.parser(),
                      extensionRegistry);
              if (dataBuilder_ == null) {
                ensureDataIsMutable();
                data_.add(m);
              } else {
                dataBuilder_.addMessage(m);
              }
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object tsid_ = "";
    /**
     * <code>string tsid = 1;</code>
     * @return The tsid.
     */
    public java.lang.String getTsid() {
      java.lang.Object ref = tsid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tsid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tsid = 1;</code>
     * @return The bytes for tsid.
     */
    public com.google.protobuf.ByteString
        getTsidBytes() {
      java.lang.Object ref = tsid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tsid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tsid = 1;</code>
     * @param value The tsid to set.
     * @return This builder for chaining.
     */
    public Builder setTsid(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tsid_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string tsid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTsid() {
      tsid_ = getDefaultInstance().getTsid();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string tsid = 1;</code>
     * @param value The bytes for tsid to set.
     * @return This builder for chaining.
     */
    public Builder setTsidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tsid_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object action_ = "";
    /**
     * <code>string action = 2;</code>
     * @return The action.
     */
    public java.lang.String getAction() {
      java.lang.Object ref = action_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        action_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string action = 2;</code>
     * @return The bytes for action.
     */
    public com.google.protobuf.ByteString
        getActionBytes() {
      java.lang.Object ref = action_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        action_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string action = 2;</code>
     * @param value The action to set.
     * @return This builder for chaining.
     */
    public Builder setAction(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      action_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string action = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAction() {
      action_ = getDefaultInstance().getAction();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string action = 2;</code>
     * @param value The bytes for action to set.
     * @return This builder for chaining.
     */
    public Builder setActionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      action_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int tstype_ ;
    /**
     * <code>int32 tstype = 3;</code>
     * @return The tstype.
     */
    @java.lang.Override
    public int getTstype() {
      return tstype_;
    }
    /**
     * <code>int32 tstype = 3;</code>
     * @param value The tstype to set.
     * @return This builder for chaining.
     */
    public Builder setTstype(int value) {

      tstype_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 tstype = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTstype() {
      bitField0_ = (bitField0_ & ~0x00000004);
      tstype_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object clz_ = "";
    /**
     * <code>string clz = 4;</code>
     * @return The clz.
     */
    public java.lang.String getClz() {
      java.lang.Object ref = clz_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clz_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string clz = 4;</code>
     * @return The bytes for clz.
     */
    public com.google.protobuf.ByteString
        getClzBytes() {
      java.lang.Object ref = clz_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clz_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string clz = 4;</code>
     * @param value The clz to set.
     * @return This builder for chaining.
     */
    public Builder setClz(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      clz_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string clz = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearClz() {
      clz_ = getDefaultInstance().getClz();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string clz = 4;</code>
     * @param value The bytes for clz to set.
     * @return This builder for chaining.
     */
    public Builder setClzBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      clz_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private int result_ ;
    /**
     * <code>int32 result = 5;</code>
     * @return The result.
     */
    @java.lang.Override
    public int getResult() {
      return result_;
    }
    /**
     * <code>int32 result = 5;</code>
     * @param value The result to set.
     * @return This builder for chaining.
     */
    public Builder setResult(int value) {

      result_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int32 result = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearResult() {
      bitField0_ = (bitField0_ & ~0x00000010);
      result_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.google.protobuf.Any> data_ =
      java.util.Collections.emptyList();
    private void ensureDataIsMutable() {
      if (!((bitField0_ & 0x00000020) != 0)) {
        data_ = new java.util.ArrayList<com.google.protobuf.Any>(data_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> dataBuilder_;

    /**
     * <code>repeated .google.protobuf.Any data = 6;</code>
     */
    public java.util.List<com.google.protobuf.Any> getDataList() {
      if (dataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(data_);
      } else {
        return dataBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .google.protobuf.Any data = 6;</code>
     */
    public int getDataCount() {
      if (dataBuilder_ == null) {
        return data_.size();
      } else {
        return dataBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .google.protobuf.Any data = 6;</code>
     */
    public com.google.protobuf.Any getData(int index) {
      if (dataBuilder_ == null) {
        return data_.get(index);
      } else {
        return dataBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .google.protobuf.Any data = 6;</code>
     */
    public Builder setData(
        int index, com.google.protobuf.Any value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataIsMutable();
        data_.set(index, value);
        onChanged();
      } else {
        dataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Any data = 6;</code>
     */
    public Builder setData(
        int index, com.google.protobuf.Any.Builder builderForValue) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.set(index, builderForValue.build());
        onChanged();
      } else {
        dataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Any data = 6;</code>
     */
    public Builder addData(com.google.protobuf.Any value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataIsMutable();
        data_.add(value);
        onChanged();
      } else {
        dataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Any data = 6;</code>
     */
    public Builder addData(
        int index, com.google.protobuf.Any value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataIsMutable();
        data_.add(index, value);
        onChanged();
      } else {
        dataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Any data = 6;</code>
     */
    public Builder addData(
        com.google.protobuf.Any.Builder builderForValue) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.add(builderForValue.build());
        onChanged();
      } else {
        dataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Any data = 6;</code>
     */
    public Builder addData(
        int index, com.google.protobuf.Any.Builder builderForValue) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.add(index, builderForValue.build());
        onChanged();
      } else {
        dataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Any data = 6;</code>
     */
    public Builder addAllData(
        java.lang.Iterable<? extends com.google.protobuf.Any> values) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, data_);
        onChanged();
      } else {
        dataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Any data = 6;</code>
     */
    public Builder clearData() {
      if (dataBuilder_ == null) {
        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        dataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Any data = 6;</code>
     */
    public Builder removeData(int index) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.remove(index);
        onChanged();
      } else {
        dataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Any data = 6;</code>
     */
    public com.google.protobuf.Any.Builder getDataBuilder(
        int index) {
      return getDataFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .google.protobuf.Any data = 6;</code>
     */
    public com.google.protobuf.AnyOrBuilder getDataOrBuilder(
        int index) {
      if (dataBuilder_ == null) {
        return data_.get(index);  } else {
        return dataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .google.protobuf.Any data = 6;</code>
     */
    public java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
         getDataOrBuilderList() {
      if (dataBuilder_ != null) {
        return dataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(data_);
      }
    }
    /**
     * <code>repeated .google.protobuf.Any data = 6;</code>
     */
    public com.google.protobuf.Any.Builder addDataBuilder() {
      return getDataFieldBuilder().addBuilder(
          com.google.protobuf.Any.getDefaultInstance());
    }
    /**
     * <code>repeated .google.protobuf.Any data = 6;</code>
     */
    public com.google.protobuf.Any.Builder addDataBuilder(
        int index) {
      return getDataFieldBuilder().addBuilder(
          index, com.google.protobuf.Any.getDefaultInstance());
    }
    /**
     * <code>repeated .google.protobuf.Any data = 6;</code>
     */
    public java.util.List<com.google.protobuf.Any.Builder> 
         getDataBuilderList() {
      return getDataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
        getDataFieldBuilder() {
      if (dataBuilder_ == null) {
        dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                data_,
                ((bitField0_ & 0x00000020) != 0),
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      return dataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.zhaoyuan.proto.auto.TSDBResponse)
  }

  // @@protoc_insertion_point(class_scope:com.zhaoyuan.proto.auto.TSDBResponse)
  private static final com.zhaoyuan.proto.auto.TSDBResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.zhaoyuan.proto.auto.TSDBResponse();
  }

  public static com.zhaoyuan.proto.auto.TSDBResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TSDBResponse>
      PARSER = new com.google.protobuf.AbstractParser<TSDBResponse>() {
    @java.lang.Override
    public TSDBResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TSDBResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TSDBResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.zhaoyuan.proto.auto.TSDBResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

