// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TSDB.proto

package com.zhaoyuan.proto.auto;

public final class TSDBProto {
  private TSDBProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zhaoyuan_proto_auto_BlobDL_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zhaoyuan_proto_auto_BlobDL_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zhaoyuan_proto_auto_BlobDLL_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zhaoyuan_proto_auto_BlobDLL_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zhaoyuan_proto_auto_TSDBRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zhaoyuan_proto_auto_TSDBRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zhaoyuan_proto_auto_TSDBResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zhaoyuan_proto_auto_TSDBResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nTSDB.proto\022\027com.zhaoyuan.proto.auto\032\031g" +
      "oogle/protobuf/any.proto\"%\n\006BlobDL\022\014\n\004da" +
      "te\030\001 \001(\t\022\r\n\005value\030\002 \001(\001\"7\n\007BlobDLL\022\014\n\004da" +
      "te\030\001 \001(\t\022\016\n\006value1\030\002 \001(\001\022\016\n\006value2\030\003 \001(\001" +
      "\"l\n\013TSDBRequest\022\014\n\004tsid\030\001 \001(\t\022\016\n\006action\030" +
      "\002 \001(\t\022\016\n\006tstype\030\003 \001(\005\022\013\n\003clz\030\004 \001(\t\022\"\n\004da" +
      "ta\030\006 \003(\0132\024.google.protobuf.Any\"}\n\014TSDBRe" +
      "sponse\022\014\n\004tsid\030\001 \001(\t\022\016\n\006action\030\002 \001(\t\022\016\n\006" +
      "tstype\030\003 \001(\005\022\013\n\003clz\030\004 \001(\t\022\016\n\006result\030\005 \001(" +
      "\005\022\"\n\004data\030\006 \003(\0132\024.google.protobuf.Any*5\n" +
      "\006ACTION\022\n\n\006CREATE\020\000\022\010\n\004READ\020\001\022\t\n\005WRITE\020\002" +
      "\022\n\n\006DELETE\020\0032\300\001\n\013TSDBService\022X\n\005write\022$." +
      "com.zhaoyuan.proto.auto.TSDBRequest\032%.co" +
      "m.zhaoyuan.proto.auto.TSDBResponse\"\000(\001\022W" +
      "\n\004read\022$.com.zhaoyuan.proto.auto.TSDBReq" +
      "uest\032%.com.zhaoyuan.proto.auto.TSDBRespo" +
      "nse\"\000(\001B\rB\tTSDBProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_com_zhaoyuan_proto_auto_BlobDL_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_zhaoyuan_proto_auto_BlobDL_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zhaoyuan_proto_auto_BlobDL_descriptor,
        new java.lang.String[] { "Date", "Value", });
    internal_static_com_zhaoyuan_proto_auto_BlobDLL_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_zhaoyuan_proto_auto_BlobDLL_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zhaoyuan_proto_auto_BlobDLL_descriptor,
        new java.lang.String[] { "Date", "Value1", "Value2", });
    internal_static_com_zhaoyuan_proto_auto_TSDBRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_zhaoyuan_proto_auto_TSDBRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zhaoyuan_proto_auto_TSDBRequest_descriptor,
        new java.lang.String[] { "Tsid", "Action", "Tstype", "Clz", "Data", });
    internal_static_com_zhaoyuan_proto_auto_TSDBResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_zhaoyuan_proto_auto_TSDBResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zhaoyuan_proto_auto_TSDBResponse_descriptor,
        new java.lang.String[] { "Tsid", "Action", "Tstype", "Clz", "Result", "Data", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
