// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TSDB.proto

package com.zhaoyuan.proto.auto;

public interface TSDBResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.zhaoyuan.proto.auto.TSDBResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tsid = 1;</code>
   * @return The tsid.
   */
  java.lang.String getTsid();
  /**
   * <code>string tsid = 1;</code>
   * @return The bytes for tsid.
   */
  com.google.protobuf.ByteString
      getTsidBytes();

  /**
   * <code>string action = 2;</code>
   * @return The action.
   */
  java.lang.String getAction();
  /**
   * <code>string action = 2;</code>
   * @return The bytes for action.
   */
  com.google.protobuf.ByteString
      getActionBytes();

  /**
   * <code>int32 tstype = 3;</code>
   * @return The tstype.
   */
  int getTstype();

  /**
   * <code>string clz = 4;</code>
   * @return The clz.
   */
  java.lang.String getClz();
  /**
   * <code>string clz = 4;</code>
   * @return The bytes for clz.
   */
  com.google.protobuf.ByteString
      getClzBytes();

  /**
   * <code>int32 result = 5;</code>
   * @return The result.
   */
  int getResult();

  /**
   * <code>repeated .google.protobuf.Any data = 6;</code>
   */
  java.util.List<com.google.protobuf.Any> 
      getDataList();
  /**
   * <code>repeated .google.protobuf.Any data = 6;</code>
   */
  com.google.protobuf.Any getData(int index);
  /**
   * <code>repeated .google.protobuf.Any data = 6;</code>
   */
  int getDataCount();
  /**
   * <code>repeated .google.protobuf.Any data = 6;</code>
   */
  java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
      getDataOrBuilderList();
  /**
   * <code>repeated .google.protobuf.Any data = 6;</code>
   */
  com.google.protobuf.AnyOrBuilder getDataOrBuilder(
      int index);
}
